#coding: utf-8
STOP_WORDS = %w{UNIVERSIDADE INSTITUTO FEDERAL EDUCAÇÃO, CIÊNCIA E TECNOLOGIA EDUCAÇÃO, ESPECIALIZAÇÃO EM - A PARA DOS NA CURSO COMO CAMPUS PARA CONCLUSÃO SUPERIOR AO MONOGRAFIA EDUCAÇÃO}

WHITESPACE = ["\n"]

EXTRA_STOP_WORDS = %w{DA DE DO}

GRADUATION = "Graduação"
SPECIALIZATION = "Especialização"
MASTERDEGREE = "Mestrado"
DOCTORAL = "Doutorado"
POSTDOCTORAL = "Pós-Doutorado"
